development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  url: postgres://localhost:5432/platform

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
