development:
  hostname: localhost:8000
  script_url: 'http://localhost:2992/_assets/main.js'
  css_url: ''


production:
  hostname: rhinobird.workslan
  script_url: '/platform/_assets/main.js'
  css_url: '/platform/_assets/main.css'
